from django.contrib.auth import views as auth
from django.urls import path
from . import views
from . import auth_views
urlpatterns=[
path("",views.home,name="home"),
path("register/",views.register,name="register"),
path("login/",auth_views.login_view,name="login"),
path("verify-otp/",auth_views.verify_otp,name="verify_otp"),
path("resend-otp/",auth_views.resend_otp,name="resend_otp"),
path("accept-invite/<uuid:token>/",auth_views.accept_invite,name="accept_invite"),
path("password-reset/",auth.PasswordResetView.as_view(template_name="registration/password_reset.html",email_template_name="emails/password_reset.txt",html_email_template_name="emails/password_reset.html",subject_template_name="emails/password_reset_subject.txt"),name="password_reset"),
path("password-reset/done/",auth.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),name="password_reset_done"),
path("reset/<uidb64>/<token>/",auth.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),name="password_reset_confirm"),
path("reset/done/",auth.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),name="password_reset_complete"),
path("logout/",auth.LogoutView.as_view(),name="logout"),
path("dashboard/",views.dashboard,name="dashboard"),
path("storyboard/",views.storyboard,name="storyboard"),
path("platform/organizations/",views.platform_organizations,name="platform_organizations"),
path("platform/organizations/<int:pk>/",views.platform_organization_detail,name="platform_organization_detail"),
path("platform/organizations/<int:pk>/status/",views.platform_organization_status,name="platform_organization_status"),
path("platform/users/",views.platform_users,name="platform_users"),
path("platform/users/<int:pk>/status/",views.platform_user_status,name="platform_user_status"),
path("platform/activity/",views.platform_activity,name="platform_activity"),
path("tasks/",views.tasks,name="tasks"),
path("tasks/new/",views.task_create,name="task_create"),
path("tasks/<int:pk>/",views.task_detail,name="task_detail"),
path("tasks/<int:pk>/status/",views.task_status,name="task_status"),
path("timesheets/",views.timesheets,name="timesheets"),
path("timesheets/new/",views.timesheet_create,name="timesheet_create"),
path("timesheets/<int:pk>/",views.timesheet_detail,name="timesheet_detail"),
path("timesheets/<int:pk>/action/",views.timesheet_action,name="timesheet_action"),
path("timesheets/<int:pk>/export/<str:fmt>/",views.timesheet_export,name="timesheet_export"),
path("employees/",views.employees,name="employees"),
path("employees/new/",views.employee_create,name="employee_create"),
path("departments/",views.departments,name="departments"),
path("documents/",views.documents,name="documents"),
path("documents/upload/",views.document_upload,name="document_upload"),
path("templates/",views.templates,name="templates"),
path("notifications/",views.notifications,name="notifications"),
path("audit/",views.audit_logs,name="audit_logs")]
