# Generated by Django 5.2.8 on 2026-08-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_emailotp_userinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_direct_reports",
                to="erp.profile",
            ),
        ),
    ]
