# Generated by Django 5.2.8 on 2026-08-27 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_chatmembership_chatpresence_chatthread_chatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="approval_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_voucher_approval",
                to="erp.task",
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="requested_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_vouchers_to_approve",
                to="erp.profile",
            ),
        ),
    ]
