# Generated by Django 5.2.8 on 2026-08-27 09:16

import django.db.models.deletion
import erp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0006_paymentvoucher_approval_task_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual leave"),
                            ("sick", "Sick leave"),
                            ("maternity", "Maternity leave"),
                            ("paternity", "Paternity leave"),
                            ("compassionate", "Compassionate leave"),
                            ("study", "Study leave"),
                            ("other", "Other leave"),
                        ],
                        default="annual",
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_message", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="erp.profile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.organization",
                    ),
                ),
                (
                    "requested_approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests_to_review",
                        to="erp.profile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual leave"),
                            ("sick", "Sick leave"),
                            ("maternity", "Maternity leave"),
                            ("paternity", "Paternity leave"),
                            ("compassionate", "Compassionate leave"),
                            ("study", "Study leave"),
                            ("other", "Other leave"),
                        ],
                        default="annual",
                        max_length=30,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(default=erp.models.current_year),
                ),
                ("allocated_days", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_leave_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocations",
                        to="erp.profile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "employee__user__first_name", "leave_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "employee", "leave_type", "year"),
                        name="unique_employee_leave_allocation",
                    )
                ],
            },
        ),
    ]
