# Generated by Django 5.2.8 on 2026-08-27 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_paymentvoucherreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="consultant_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="consultant_signature",
            field=models.ImageField(
                blank=True, upload_to="timesheet_signatures/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="contract_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="expert_signature",
            field=models.ImageField(
                blank=True, upload_to="timesheet_signatures/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="financing",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="initial_budget_days",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="manager_signature",
            field=models.ImageField(
                blank=True, upload_to="timesheet_signatures/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="place_of_assignment",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="service_contract",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="days_worked",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Country, city and region where services were provided",
                max_length=180,
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="overnight_duty_station",
            field=models.BooleanField(
                default=False, verbose_name="Overnight stay in duty-station country"
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="overnight_outside_duty_station",
            field=models.BooleanField(
                default=False,
                verbose_name="Overnight stay outside duty-station country",
            ),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="per_diem_requested",
            field=models.BooleanField(default=False, verbose_name="Per diem requested"),
        ),
        migrations.AddConstraint(
            model_name="timesheet",
            constraint=models.UniqueConstraint(
                fields=("organization", "employee", "period_start"),
                name="unique_monthly_timesheet_per_employee",
            ),
        ),
    ]
