# Generated by Django 5.2.8 on 2026-08-27 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_timesheet_consultant_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="request_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_timesheet",
                to="erp.task",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="requested_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets_to_approve",
                to="erp.profile",
            ),
        ),
    ]
